### ISSUE TITLE
Unexpected token import: ES2015 module support without transpiling to CommonJS

### ISSUE THREAD

**Issue by CKGrafico** [andywer/ava-ts#5]
I've made a simple test like your example and I've this error:
```
(function (exports, require, module, __filename, __dirname) { import test from 'ava';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

the test:
```
import test from 'ava';

test('one plus two equals three', t => {
  t.is(1 + 2, 3);
});
```

**Comment by andywer** [comment]
Hey @CKGrafico! It's a bit too little information to debug. What does your `tsconfig.json` look like? I guess `target` or `module` is not set correctly.

You can also have a look at [andywer/key-store](https://github.com/andywer/key-store).

**Comment by CKGrafico** [comment]
Ups sorry, the tsconfig is the default tsconfig of nuxt typescript example https://github.com/nuxt/nuxt.js/blob/dev/examples/typescript/tsconfig.json

**Comment by andywer** [comment]
Can't really help here, I fear, since I would need to have access to a project that reproduces the issue.

I can only suggest you have a look at `andywer/key-store` and compare, since it uses es2015 modules and works just fine.

**Comment by CKGrafico** [comment]
You can clone this repo http://bit.ly/2BHkpRV is public :) by the moment I've added mocha for the tests but the community of nuxt is using ava and we want to try

**Comment by andywer** [comment]
Update: I think you have to set `"module": "commonjs"` instead of `"module": "es2015"` in your `tsconfig.json`. The setting describes what to compile it to.

If it's set to `es2015`, it will output ES2015 modules and node will choke upon it 😉

**Comment by CKGrafico** [comment]
Ok in this case I can't use ava thanks

**Comment by mastilver** [comment]
Hi

I'm having the same issue

Is there any way to override the tsconfig used by `ts-ava` like `ava` is doing?
https://github.com/avajs/ava#es2017-support

**Comment by andywer** [comment]
Hey @mastilver. Yeah, just add a `tsconfig.json` file to your project and set the appropriate settings (`"module": "commonjs"` should be the solution here).

Should probably add a FAQ section to the readme.

**Comment by mastilver** [comment]
Thank you for the quick answer!! :)

I already have `module` set to `es2015` and I need it that way, I was wondering if it could be overwritten only when using `ts-ava`

**Comment by andywer** [comment]
Hmmm... Maybe conditionally loading <https://github.com/standard-things/esm> together with `ts-node` would solve the issue.

Will re-open the issue and change the title.

Can you check if monkey-patching [api.js](https://github.com/andywer/ava-ts/blob/7563e3bf1d284a437cd44263eba312929799e37e/api.js#L56) to load `esm` works?

**Comment by mastilver** [comment]
Thank you so much

This worked for me:

```
"ava": {
    "require": ["ts-node/register", "@std/esm"]
  }
```

**Comment by andywer** [comment]
Awesome! Will add a FAQ section later. That should do for the moment :)

@CKGrafico That sounds like good news for you, too.

**Comment by CKGrafico** [comment]
I can't invest time on this for now, but yes if you need ts node probably a config like the project mentioned before will works  http://bit.ly/2BHkpRV  by the moment I will use mocha because I've all working from other projects but change to ava with this config have to be easy

**Comment by andywer** [comment]
@all Better late than never... There is an easy solution!

You can just set the `TS_NODE_COMPILER_OPTIONS` env variable to set `module` to `commonjs`. Will update the README.

We should probably have a command line parameter for that, though.

**Comment by seiyria** [comment]
this definitely needs a CLI parameter IMO.

**Comment by andywer** [comment]
@seiyria Fair enough, but #24 needs to be decided on first and that's a tricky one. Will be easier once I found the time to use AVA v1.0 with TypeScript a couple more times.
