### ISSUE TITLE
ts-node peer dependency

### ISSUE THREAD

**Issue by Gerrit0** [andywer/ava-ts#6]
Hello, 

I am looking to use this in a few projects that keep dependencies up to date with greenkeeper. As such, I would like to use the latest version of `ts-node`. `ava-ts` has a peer dependency on `ts-node@^3.0.0`. Is an update to target the latest version possible? I have tried installing the latest version and everything seems to work, but I may be missing things since I am unfamiliar with how everything ties together. 

Thanks
Gerrit

**Comment by andywer** [comment]
Hey @Gerrit0!

Good point. Looks like they made `ts-node` [not type-check by default in v4](https://github.com/TypeStrong/ts-node/releases/tag/v4.0.0).

We will probably need to set `process.env.TS_NODE_TYPE_CHECK`, but that should not be an issue.

I will have a look and update in time 🙂
